### ISSUE TITLE
Mod doesn't work on servers.

### ISSUE THREAD

**Issue by AzureDoom** [baguchan/BagusLib#1]
[05.06 20:01:21] [Server] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid bagus_lib
[05.06 20:01:21] [Server] java.lang.BootstrapMethodErrorjava.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
[05.06 20:01:21] [Server] 	at bagu_chan.bagus_lib.BagusLib.setupMessages(BagusLib.java:60) ~[Baguslib-1.19.4-1.4.0.jar%23205!/:1.19.4-1.4.{re:classloading}
[05.06 20:01:21] [Server] 	at bagu_chan.bagus_lib.BagusLib.commonSetup(BagusLib.java:72) ~[Baguslib-1.19.4-1.4.0.jar%23205!/:1.19.4-1.4.{re:classloading}

**Comment by baguchi** [comment]
sorry for late.
1.19.4-1.4.1 will be fixed!
