### ISSUE TITLE
[1.20.1-3.0.0] Mod uses library that is not available on servers - org/apache/commons/compress/utils/Lists

### ISSUE THREAD

**Issue by TigerWalts** [baguchan/BagusLib#2]
```
-- Head --
Thread: main
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD bagus_lib --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
		at bagu_chan.bagus_lib.util.TierHelper.<clinit>(TierHelper.java:20) ~[Baguslib-1.20.1-3.0.0.jar%23203!/:1.20.1-3.0.0] {re:classloading}
		at bagu_chan.bagus_lib.BagusLib.commonSetup(BagusLib.java:48) ~[Baguslib-1.20.1-3.0.0.jar%23203!/:1.20.1-3.0.0] {re:classloading}
```

https://github.com/baguchan/BagusLib/blob/7ab44c99f82f8932f5fdef09add96250ffdd13ab/src/main/java/bagu_chan/bagus_lib/util/TierHelper.java#L20

`commons-compress` is not available on Forge mod dedicated servers.

**Comment by baguchi** [comment]
fixed! thanks for finding!
