### ISSUE TITLE
log spam with NeoForge

### ISSUE THREAD

**Issue by Lolothepro** [baguchan/BagusLib#8]
```
[minecraft/BlockableEventLoop]: Error executing task on Server
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Receiver class net.minecraft.world.entity.ambient.Bat does not define or inherit an implementation of the resolved method 'abstract void resync(net.minecraft.world.entity.Entity)' of interface bagu_chan.bagus_lib.api.IBaguPacket.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?] {}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:810) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:162) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:793) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:787) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:130) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:774) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:704) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:255) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
Caused by: java.lang.AbstractMethodError: Receiver class net.minecraft.world.entity.ambient.Bat does not define or inherit an implementation of the resolved method 'abstract void resync(net.minecraft.world.entity.Entity)' of interface bagu_chan.bagus_lib.api.IBaguPacket.
	at bagu_chan.bagus_lib.message.SyncEntityPacketToServer.lambda$handle$0(SyncEntityPacketToServer.java:50) ~[bagus_lib-1.20.4-8.4.0.jar%23314!/:?] {re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	... 13 more
[11:45:18] [Server thread/ERROR] [ne.ne.ne.ne.re.NetworkRegistry$EventLoopSynchronizedWorkHandler/]: Failed to process a synchronized task of the payload: bagu_chan.bagus_lib.message.SyncEntityPacketToServer@64af5ddd
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Receiver class net.minecraft.world.entity.ambient.Bat does not define or inherit an implementation of the resolved method 'abstract void resync(net.minecraft.world.entity.Entity)' of interface bagu_chan.bagus_lib.api.IBaguPacket.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?] {}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:810) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:162) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:793) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:787) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:130) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:774) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:704) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:255) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
Caused by: java.lang.AbstractMethodError: Receiver class net.minecraft.world.entity.ambient.Bat does not define or inherit an implementation of the resolved method 'abstract void resync(net.minecraft.world.entity.Entity)' of interface bagu_chan.bagus_lib.api.IBaguPacket.
	at bagu_chan.bagus_lib.message.SyncEntityPacketToServer.lambda$handle$0(SyncEntityPacketToServer.java:50) ~[bagus_lib-1.20.4-8.4.0.jar%23314!/:?] {re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[client-1.20.4-20231207.154220-srg.jar%23442!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	... 13 more
```

[latest.log](https://github.com/baguchan/BagusLib/files/14322163/latest.log)

Is it possible to fix this?
I don't know if it's due to your mods, but I think so.

**Comment by baguchi** [comment]
mayby another my mod's problem(such as EnchantWithMob)

**Comment by baguchi** [comment]
I checked with run my server(EnchantWithMob and BagusLib only) Nothing happened....

**Comment by Lolothepro** [comment]
Even with "Bagus Lib", "BagusMob" and "EnchantWithMob" I have lots of errors in the log file.
https://mclo.gs/YTCM9BA

**Comment by Lolothepro** [comment]
This may be due to a NeoForge update.

**Comment by baguchi** [comment]
hmm mayby?
