### ISSUE TITLE
[1.21-11.0.0] Server crash - Attempted to load class net/minecraft/client/resources/sounds/SoundInstance for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by TigerWalts** [baguchan/BagusLib#9]
- [Crash Report](https://mclo.gs/Hfe0VOY)

```
	Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/sounds/SoundInstance for invalid dist DEDICATED_SERVER
		at TRANSFORMER/bagus_lib@1.21-11.0.0/bagu_chan.bagus_lib.register.ModDialogs.<clinit>(ModDialogs.java:25) ~[bagus_lib-1.21-11.0.0.jar%23180!/:?] {re:classloading}
		at TRANSFORMER/bagus_lib@1.21-11.0.0/bagu_chan.bagus_lib.BagusLib.<init>(BagusLib.java:36) ~[bagus_lib-1.21-11.0.0.jar%23180!/:?] {re:classloading}
```

**Comment by baguchi** [comment]
thanks for reporting!
I'll fix in next version!
